name: TotalComputers
version: 1.0
author: JNNGL
main: com.jnngl.totalcomputers.TotalComputers
api-version: 1.12.2

commands:
  totalcomputers:
    description: Command for TotalComputers plugin.
    usage: /totalcomputers [...]
    permission: totalcomputers.command.totalcomputers
    permission-message: You don't have enough permissions to use this command.
    aliases:
      - tcomputers
      - tcmp

permissions:
  totalcomputers.command.totalcomputers:
    description: Allows to use command
    default: op
  totalcomputers.selection:
    description: Allows to select area using diamonf hoe
    default: op
  totalcomputers.use:
    description: Allows to use computers
    default: true
  totalcomputers.admin:
    description: Allows to use computers as administrator.
    default: op